### ISSUE TITLE
Why not io_uring?

### ISSUE THREAD

**Issue by pickfire** [errantmind/faf#1]
I saw online saying that io_uring should be faster, is there any reason why io_uring is not used?

Demo io_uring have some benchmark. https://github.com/frevib/io_uring-echo-server/blob/master/benchmarks/benchmarks.md

**Comment by errantmind** [comment]
Three reasons: 

1. In my experiments it is slower than epoll for this. My last set of tests were in Feb of last year so maybe it is faster now. 
2. The io_uring API had a lot of.. rough edges
3. The benchmark server didn't have a new enough kernel for io_uring when I started the project in Feb of last year

I will probably create an io_uring version of this sometime this year if I have time.

**Comment by pickfire** [comment]
Thanks for the quick response, that answered my question. I guess I will just close this then.
