### ISSUE TITLE
have u looked at monoio / glommio? will it be faster? 

### ISSUE THREAD

**Issue by hiqsociety** [errantmind/faf#2]
what's ur opinion on this coz it's using io_uring... is this possible that much faster than faf?
https://betterprogramming.pub/gain-the-new-fastest-go-tcp-framework-40ec111d40e6

how does faf perform under
1. more than 16 cpu cores? ( normally 32 cores will show low req/s beyond 8 cores, see monoio benchmark)
2. multiple concurrent connections > 500,000 simultaneous connections? (looking at using as websocket)

great work by the way, v impressive.

**Comment by errantmind** [comment]
`io_uring` has some promise, but last I checked the tfb benchmarks are running under an older kernel, so I stopped my testing in that area until they update their kernel version. Also, tfb benchmarks are network bottlenecked at the moment, so the top frameworks are 'capped', making it hard to distinguish which are actually the best (once they get to ~7m req/s on the charts). I'd really like to see them auto-update to the latest mainline kernel, and upgrade their network to 100GbE.

1. FaF appears to scale well with more cores. 
2. I haven't tested that high of simultaneous connections. In theory FaF could be tested with that many if a couple constants in the project are adjusted and the OS configuration is also adjusted to allow bigger stack sizes for the project's buffers. By default, FaF supports up to 32K concurrent connections. Epoll may have a lot of overhead polling 500k active descriptors so other approaches like `io_uring` may be superior.

**Comment by errantmind** [comment]
I decided to take a closer look and realized he has posted no code. I'm surprised he actually posted an article like that without code to back it up. Tenuous at best, but that doesn't mean I won't be interested to take a look once he gets around to it.

Feel free to post another issue once he posts code if you are still interested at that point.
